[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.12.0", features = ["serialize"] }
bevy_renet = { workspace = true }
rust-ini = { workspace = true }
toml = { workspace = true }
shared = { path = "../shared" }
bincode = { workspace = true }
serde = { workspace = true }